<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- 
        6.promise异常传透？
            .当使用promise的then链式调用时，可以在最后指定失败的回调，
            .前面任何操作除了异常，都会传到最后失败的回调中处理
        7.中断promise链
            .当使用promise的then链式调用时，在中间中断，不再调用后面的回调函数
            .办法：在回调函数中返回一个pendding状态的promise对象
     -->
    <script>
 new Promise((resolve, reject) => {
        resolve('wangxia')
        //reject(1)
      }).then(
        (value) => {
          console.log("onResolved1()", value)
          return 2
        }
      ).then(
        (value) => {
          console.log("onResolved2()", value);
          return 3
        },
        reason => {throw reason}
      ).then(
        (value) => {
          console.log("onResolved3()", value);
        },
        reason => Promise.reject(reason)
      )
      .catch(
        (reason) => {
          console.log("onRejected1()", reason);
          return new Promise(() => {})  //返回一个pendding的promise,这样就可以中断promise链
        }
      ).then(
        (value) => {
          console.log("onResolved3()", value);
        },
        reason => {
            console.log("onRejected2()", reason);
        }
      )
    </script>
</body>
</html>